/*
 * This file is automatically generated at Mon, 12 Aug 2013 14:47:22 +0300
 *
 * Class: android.content.Context
 * Jar: /home/D.Iakovliev/android/android-sdk-linux/platforms/android-14/android.jar
 *
 * !!!! DO NOT EDIT THIS FILE !!!!
 */
#ifndef _Context_genheader
#define _Context_genheader

static JavaMember Context[] = {
  /* public static final int MODE_PRIVATE; */
  { Int, Static|Final|Public|Field, "MODE_PRIVATE", "MODE_PRIVATE", "I" },
  /* public static final int MODE_WORLD_READABLE; */
  { Int, Static|Final|Public|Field, "MODE_WORLD_READABLE", "MODE_WORLD_READABLE", "I" },
  /* public static final int MODE_WORLD_WRITEABLE; */
  { Int, Static|Final|Public|Field, "MODE_WORLD_WRITEABLE", "MODE_WORLD_WRITEABLE", "I" },
  /* public static final int MODE_APPEND; */
  { Int, Static|Final|Public|Field, "MODE_APPEND", "MODE_APPEND", "I" },
  /* public static final int MODE_MULTI_PROCESS; */
  { Int, Static|Final|Public|Field, "MODE_MULTI_PROCESS", "MODE_MULTI_PROCESS", "I" },
  /* public static final int BIND_AUTO_CREATE; */
  { Int, Static|Final|Public|Field, "BIND_AUTO_CREATE", "BIND_AUTO_CREATE", "I" },
  /* public static final int BIND_DEBUG_UNBIND; */
  { Int, Static|Final|Public|Field, "BIND_DEBUG_UNBIND", "BIND_DEBUG_UNBIND", "I" },
  /* public static final int BIND_NOT_FOREGROUND; */
  { Int, Static|Final|Public|Field, "BIND_NOT_FOREGROUND", "BIND_NOT_FOREGROUND", "I" },
  /* public static final int BIND_ABOVE_CLIENT; */
  { Int, Static|Final|Public|Field, "BIND_ABOVE_CLIENT", "BIND_ABOVE_CLIENT", "I" },
  /* public static final int BIND_ALLOW_OOM_MANAGEMENT; */
  { Int, Static|Final|Public|Field, "BIND_ALLOW_OOM_MANAGEMENT", "BIND_ALLOW_OOM_MANAGEMENT", "I" },
  /* public static final int BIND_WAIVE_PRIORITY; */
  { Int, Static|Final|Public|Field, "BIND_WAIVE_PRIORITY", "BIND_WAIVE_PRIORITY", "I" },
  /* public static final int BIND_IMPORTANT; */
  { Int, Static|Final|Public|Field, "BIND_IMPORTANT", "BIND_IMPORTANT", "I" },
  /* public static final int BIND_ADJUST_WITH_ACTIVITY; */
  { Int, Static|Final|Public|Field, "BIND_ADJUST_WITH_ACTIVITY", "BIND_ADJUST_WITH_ACTIVITY", "I" },
  /* public static final java.lang.String POWER_SERVICE; */
  { Object, Static|Final|Public|Field, "POWER_SERVICE", "POWER_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String WINDOW_SERVICE; */
  { Object, Static|Final|Public|Field, "WINDOW_SERVICE", "WINDOW_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String LAYOUT_INFLATER_SERVICE; */
  { Object, Static|Final|Public|Field, "LAYOUT_INFLATER_SERVICE", "LAYOUT_INFLATER_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String ACCOUNT_SERVICE; */
  { Object, Static|Final|Public|Field, "ACCOUNT_SERVICE", "ACCOUNT_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String ACTIVITY_SERVICE; */
  { Object, Static|Final|Public|Field, "ACTIVITY_SERVICE", "ACTIVITY_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String ALARM_SERVICE; */
  { Object, Static|Final|Public|Field, "ALARM_SERVICE", "ALARM_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String NOTIFICATION_SERVICE; */
  { Object, Static|Final|Public|Field, "NOTIFICATION_SERVICE", "NOTIFICATION_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String ACCESSIBILITY_SERVICE; */
  { Object, Static|Final|Public|Field, "ACCESSIBILITY_SERVICE", "ACCESSIBILITY_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String KEYGUARD_SERVICE; */
  { Object, Static|Final|Public|Field, "KEYGUARD_SERVICE", "KEYGUARD_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String LOCATION_SERVICE; */
  { Object, Static|Final|Public|Field, "LOCATION_SERVICE", "LOCATION_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String SEARCH_SERVICE; */
  { Object, Static|Final|Public|Field, "SEARCH_SERVICE", "SEARCH_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String SENSOR_SERVICE; */
  { Object, Static|Final|Public|Field, "SENSOR_SERVICE", "SENSOR_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String STORAGE_SERVICE; */
  { Object, Static|Final|Public|Field, "STORAGE_SERVICE", "STORAGE_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String WALLPAPER_SERVICE; */
  { Object, Static|Final|Public|Field, "WALLPAPER_SERVICE", "WALLPAPER_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String VIBRATOR_SERVICE; */
  { Object, Static|Final|Public|Field, "VIBRATOR_SERVICE", "VIBRATOR_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String CONNECTIVITY_SERVICE; */
  { Object, Static|Final|Public|Field, "CONNECTIVITY_SERVICE", "CONNECTIVITY_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String WIFI_SERVICE; */
  { Object, Static|Final|Public|Field, "WIFI_SERVICE", "WIFI_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String WIFI_P2P_SERVICE; */
  { Object, Static|Final|Public|Field, "WIFI_P2P_SERVICE", "WIFI_P2P_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String AUDIO_SERVICE; */
  { Object, Static|Final|Public|Field, "AUDIO_SERVICE", "AUDIO_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String TELEPHONY_SERVICE; */
  { Object, Static|Final|Public|Field, "TELEPHONY_SERVICE", "TELEPHONY_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String CLIPBOARD_SERVICE; */
  { Object, Static|Final|Public|Field, "CLIPBOARD_SERVICE", "CLIPBOARD_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String INPUT_METHOD_SERVICE; */
  { Object, Static|Final|Public|Field, "INPUT_METHOD_SERVICE", "INPUT_METHOD_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String TEXT_SERVICES_MANAGER_SERVICE; */
  { Object, Static|Final|Public|Field, "TEXT_SERVICES_MANAGER_SERVICE", "TEXT_SERVICES_MANAGER_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String DROPBOX_SERVICE; */
  { Object, Static|Final|Public|Field, "DROPBOX_SERVICE", "DROPBOX_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String DEVICE_POLICY_SERVICE; */
  { Object, Static|Final|Public|Field, "DEVICE_POLICY_SERVICE", "DEVICE_POLICY_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String UI_MODE_SERVICE; */
  { Object, Static|Final|Public|Field, "UI_MODE_SERVICE", "UI_MODE_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String DOWNLOAD_SERVICE; */
  { Object, Static|Final|Public|Field, "DOWNLOAD_SERVICE", "DOWNLOAD_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String NFC_SERVICE; */
  { Object, Static|Final|Public|Field, "NFC_SERVICE", "NFC_SERVICE", "Ljava/lang/String;" },
  /* public static final java.lang.String USB_SERVICE; */
  { Object, Static|Final|Public|Field, "USB_SERVICE", "USB_SERVICE", "Ljava/lang/String;" },
  /* public static final int CONTEXT_INCLUDE_CODE; */
  { Int, Static|Final|Public|Field, "CONTEXT_INCLUDE_CODE", "CONTEXT_INCLUDE_CODE", "I" },
  /* public static final int CONTEXT_IGNORE_SECURITY; */
  { Int, Static|Final|Public|Field, "CONTEXT_IGNORE_SECURITY", "CONTEXT_IGNORE_SECURITY", "I" },
  /* public static final int CONTEXT_RESTRICTED; */
  { Int, Static|Final|Public|Field, "CONTEXT_RESTRICTED", "CONTEXT_RESTRICTED", "I" },
  /* public android.content.Context(); */
  { Void, Public|Constructor, "<init>", "<init>", "()V" },
  /* public abstract android.content.res.AssetManager getAssets(); */
  { Object, Abstract|Public|Function, "getAssets", "getAssets", "()Landroid/content/res/AssetManager;" },
  /* public abstract android.content.res.Resources getResources(); */
  { Object, Abstract|Public|Function, "getResources", "getResources", "()Landroid/content/res/Resources;" },
  /* public abstract android.content.pm.PackageManager getPackageManager(); */
  { Object, Abstract|Public|Function, "getPackageManager", "getPackageManager", "()Landroid/content/pm/PackageManager;" },
  /* public abstract android.content.ContentResolver getContentResolver(); */
  { Object, Abstract|Public|Function, "getContentResolver", "getContentResolver", "()Landroid/content/ContentResolver;" },
  /* public abstract android.os.Looper getMainLooper(); */
  { Object, Abstract|Public|Function, "getMainLooper", "getMainLooper", "()Landroid/os/Looper;" },
  /* public abstract android.content.Context getApplicationContext(); */
  { Object, Abstract|Public|Function, "getApplicationContext", "getApplicationContext", "()Landroid/content/Context;" },
  /* public void registerComponentCallbacks(android.content.ComponentCallbacks); */
  { Void, Public|Function, "registerComponentCallbacks", "registerComponentCallbacks", "(Landroid/content/ComponentCallbacks;)V" },
  /* public void unregisterComponentCallbacks(android.content.ComponentCallbacks); */
  { Void, Public|Function, "unregisterComponentCallbacks", "unregisterComponentCallbacks", "(Landroid/content/ComponentCallbacks;)V" },
  /* public final java.lang.CharSequence getText(int); */
  { Object, Final|Public|Function, "getText", "getText", "(I)Ljava/lang/CharSequence;" },
  /* public final java.lang.String getString(int); */
  { Object, Final|Public|Function, "getString", "getString", "(I)Ljava/lang/String;" },
  /* public final java.lang.String getString(int, java.lang.Object[]); */
  { Object, Final|Public|Function, "getString_0", "getString", "(I[Ljava/lang/Object;)Ljava/lang/String;" },
  /* public abstract void setTheme(int); */
  { Void, Abstract|Public|Function, "setTheme", "setTheme", "(I)V" },
  /* public abstract android.content.res.Resources$Theme getTheme(); */
  { Object, Abstract|Public|Function, "getTheme", "getTheme", "()Landroid/content/res/Resources$Theme;" },
  /* public final android.content.res.TypedArray obtainStyledAttributes(int[]); */
  { Object, Final|Public|Function, "obtainStyledAttributes", "obtainStyledAttributes", "([I)Landroid/content/res/TypedArray;" },
  /* public final android.content.res.TypedArray obtainStyledAttributes(int, int[])   throws android.content.res.Resources$NotFoundException; */
  { Object, Final|Public|Function, "obtainStyledAttributes_1", "obtainStyledAttributes", "(I[I)Landroid/content/res/TypedArray;" },
  /* public final android.content.res.TypedArray obtainStyledAttributes(android.util.AttributeSet, int[]); */
  { Object, Final|Public|Function, "obtainStyledAttributes_2", "obtainStyledAttributes", "(Landroid/util/AttributeSet;[I)Landroid/content/res/TypedArray;" },
  /* public final android.content.res.TypedArray obtainStyledAttributes(android.util.AttributeSet, int[], int, int); */
  { Object, Final|Public|Function, "obtainStyledAttributes_3", "obtainStyledAttributes", "(Landroid/util/AttributeSet;[III)Landroid/content/res/TypedArray;" },
  /* public abstract java.lang.ClassLoader getClassLoader(); */
  { Object, Abstract|Public|Function, "getClassLoader", "getClassLoader", "()Ljava/lang/ClassLoader;" },
  /* public abstract java.lang.String getPackageName(); */
  { Object, Abstract|Public|Function, "getPackageName", "getPackageName", "()Ljava/lang/String;" },
  /* public abstract android.content.pm.ApplicationInfo getApplicationInfo(); */
  { Object, Abstract|Public|Function, "getApplicationInfo", "getApplicationInfo", "()Landroid/content/pm/ApplicationInfo;" },
  /* public abstract java.lang.String getPackageResourcePath(); */
  { Object, Abstract|Public|Function, "getPackageResourcePath", "getPackageResourcePath", "()Ljava/lang/String;" },
  /* public abstract java.lang.String getPackageCodePath(); */
  { Object, Abstract|Public|Function, "getPackageCodePath", "getPackageCodePath", "()Ljava/lang/String;" },
  /* public abstract android.content.SharedPreferences getSharedPreferences(java.lang.String, int); */
  { Object, Abstract|Public|Function, "getSharedPreferences", "getSharedPreferences", "(Ljava/lang/String;I)Landroid/content/SharedPreferences;" },
  /* public abstract java.io.FileInputStream openFileInput(java.lang.String)   throws java.io.FileNotFoundException; */
  { Object, Abstract|Public|Function, "openFileInput", "openFileInput", "(Ljava/lang/String;)Ljava/io/FileInputStream;" },
  /* public abstract java.io.FileOutputStream openFileOutput(java.lang.String, int)   throws java.io.FileNotFoundException; */
  { Object, Abstract|Public|Function, "openFileOutput", "openFileOutput", "(Ljava/lang/String;I)Ljava/io/FileOutputStream;" },
  /* public abstract boolean deleteFile(java.lang.String); */
  { Boolean, Abstract|Public|Function, "deleteFile", "deleteFile", "(Ljava/lang/String;)Z" },
  /* public abstract java.io.File getFileStreamPath(java.lang.String); */
  { Object, Abstract|Public|Function, "getFileStreamPath", "getFileStreamPath", "(Ljava/lang/String;)Ljava/io/File;" },
  /* public abstract java.io.File getFilesDir(); */
  { Object, Abstract|Public|Function, "getFilesDir", "getFilesDir", "()Ljava/io/File;" },
  /* public abstract java.io.File getExternalFilesDir(java.lang.String); */
  { Object, Abstract|Public|Function, "getExternalFilesDir", "getExternalFilesDir", "(Ljava/lang/String;)Ljava/io/File;" },
  /* public abstract java.io.File getObbDir(); */
  { Object, Abstract|Public|Function, "getObbDir", "getObbDir", "()Ljava/io/File;" },
  /* public abstract java.io.File getCacheDir(); */
  { Object, Abstract|Public|Function, "getCacheDir", "getCacheDir", "()Ljava/io/File;" },
  /* public abstract java.io.File getExternalCacheDir(); */
  { Object, Abstract|Public|Function, "getExternalCacheDir", "getExternalCacheDir", "()Ljava/io/File;" },
  /* public abstract java.lang.String[] fileList(); */
  { Object, Abstract|Public|Function, "fileList", "fileList", "()[Ljava/lang/String;" },
  /* public abstract java.io.File getDir(java.lang.String, int); */
  { Object, Abstract|Public|Function, "getDir", "getDir", "(Ljava/lang/String;I)Ljava/io/File;" },
  /* public abstract android.database.sqlite.SQLiteDatabase openOrCreateDatabase(java.lang.String, int, android.database.sqlite.SQLiteDatabase$CursorFactory); */
  { Object, Abstract|Public|Function, "openOrCreateDatabase", "openOrCreateDatabase", "(Ljava/lang/String;ILandroid/database/sqlite/SQLiteDatabase$CursorFactory;)Landroid/database/sqlite/SQLiteDatabase;" },
  /* public abstract android.database.sqlite.SQLiteDatabase openOrCreateDatabase(java.lang.String, int, android.database.sqlite.SQLiteDatabase$CursorFactory, android.database.DatabaseErrorHandler); */
  { Object, Abstract|Public|Function, "openOrCreateDatabase_4", "openOrCreateDatabase", "(Ljava/lang/String;ILandroid/database/sqlite/SQLiteDatabase$CursorFactory;Landroid/database/DatabaseErrorHandler;)Landroid/database/sqlite/SQLiteDatabase;" },
  /* public abstract boolean deleteDatabase(java.lang.String); */
  { Boolean, Abstract|Public|Function, "deleteDatabase", "deleteDatabase", "(Ljava/lang/String;)Z" },
  /* public abstract java.io.File getDatabasePath(java.lang.String); */
  { Object, Abstract|Public|Function, "getDatabasePath", "getDatabasePath", "(Ljava/lang/String;)Ljava/io/File;" },
  /* public abstract java.lang.String[] databaseList(); */
  { Object, Abstract|Public|Function, "databaseList", "databaseList", "()[Ljava/lang/String;" },
  /* public abstract android.graphics.drawable.Drawable getWallpaper(); */
  { Object, Abstract|Public|Function, "getWallpaper", "getWallpaper", "()Landroid/graphics/drawable/Drawable;" },
  /* public abstract android.graphics.drawable.Drawable peekWallpaper(); */
  { Object, Abstract|Public|Function, "peekWallpaper", "peekWallpaper", "()Landroid/graphics/drawable/Drawable;" },
  /* public abstract int getWallpaperDesiredMinimumWidth(); */
  { Int, Abstract|Public|Function, "getWallpaperDesiredMinimumWidth", "getWallpaperDesiredMinimumWidth", "()I" },
  /* public abstract int getWallpaperDesiredMinimumHeight(); */
  { Int, Abstract|Public|Function, "getWallpaperDesiredMinimumHeight", "getWallpaperDesiredMinimumHeight", "()I" },
  /* public abstract void setWallpaper(android.graphics.Bitmap)   throws java.io.IOException; */
  { Void, Abstract|Public|Function, "setWallpaper", "setWallpaper", "(Landroid/graphics/Bitmap;)V" },
  /* public abstract void setWallpaper(java.io.InputStream)   throws java.io.IOException; */
  { Void, Abstract|Public|Function, "setWallpaper_5", "setWallpaper", "(Ljava/io/InputStream;)V" },
  /* public abstract void clearWallpaper()   throws java.io.IOException; */
  { Void, Abstract|Public|Function, "clearWallpaper", "clearWallpaper", "()V" },
  /* public abstract void startActivity(android.content.Intent); */
  { Void, Abstract|Public|Function, "startActivity", "startActivity", "(Landroid/content/Intent;)V" },
  /* public abstract void startActivities(android.content.Intent[]); */
  { Void, Abstract|Public|Function, "startActivities", "startActivities", "([Landroid/content/Intent;)V" },
  /* public abstract void startIntentSender(android.content.IntentSender, android.content.Intent, int, int, int)   throws android.content.IntentSender$SendIntentException; */
  { Void, Abstract|Public|Function, "startIntentSender", "startIntentSender", "(Landroid/content/IntentSender;Landroid/content/Intent;III)V" },
  /* public abstract void sendBroadcast(android.content.Intent); */
  { Void, Abstract|Public|Function, "sendBroadcast", "sendBroadcast", "(Landroid/content/Intent;)V" },
  /* public abstract void sendBroadcast(android.content.Intent, java.lang.String); */
  { Void, Abstract|Public|Function, "sendBroadcast_6", "sendBroadcast", "(Landroid/content/Intent;Ljava/lang/String;)V" },
  /* public abstract void sendOrderedBroadcast(android.content.Intent, java.lang.String); */
  { Void, Abstract|Public|Function, "sendOrderedBroadcast", "sendOrderedBroadcast", "(Landroid/content/Intent;Ljava/lang/String;)V" },
  /* public abstract void sendOrderedBroadcast(android.content.Intent, java.lang.String, android.content.BroadcastReceiver, android.os.Handler, int, java.lang.String, android.os.Bundle); */
  { Void, Abstract|Public|Function, "sendOrderedBroadcast_7", "sendOrderedBroadcast", "(Landroid/content/Intent;Ljava/lang/String;Landroid/content/BroadcastReceiver;Landroid/os/Handler;ILjava/lang/String;Landroid/os/Bundle;)V" },
  /* public abstract void sendStickyBroadcast(android.content.Intent); */
  { Void, Abstract|Public|Function, "sendStickyBroadcast", "sendStickyBroadcast", "(Landroid/content/Intent;)V" },
  /* public abstract void sendStickyOrderedBroadcast(android.content.Intent, android.content.BroadcastReceiver, android.os.Handler, int, java.lang.String, android.os.Bundle); */
  { Void, Abstract|Public|Function, "sendStickyOrderedBroadcast", "sendStickyOrderedBroadcast", "(Landroid/content/Intent;Landroid/content/BroadcastReceiver;Landroid/os/Handler;ILjava/lang/String;Landroid/os/Bundle;)V" },
  /* public abstract void removeStickyBroadcast(android.content.Intent); */
  { Void, Abstract|Public|Function, "removeStickyBroadcast", "removeStickyBroadcast", "(Landroid/content/Intent;)V" },
  /* public abstract android.content.Intent registerReceiver(android.content.BroadcastReceiver, android.content.IntentFilter); */
  { Object, Abstract|Public|Function, "registerReceiver", "registerReceiver", "(Landroid/content/BroadcastReceiver;Landroid/content/IntentFilter;)Landroid/content/Intent;" },
  /* public abstract android.content.Intent registerReceiver(android.content.BroadcastReceiver, android.content.IntentFilter, java.lang.String, android.os.Handler); */
  { Object, Abstract|Public|Function, "registerReceiver_8", "registerReceiver", "(Landroid/content/BroadcastReceiver;Landroid/content/IntentFilter;Ljava/lang/String;Landroid/os/Handler;)Landroid/content/Intent;" },
  /* public abstract void unregisterReceiver(android.content.BroadcastReceiver); */
  { Void, Abstract|Public|Function, "unregisterReceiver", "unregisterReceiver", "(Landroid/content/BroadcastReceiver;)V" },
  /* public abstract android.content.ComponentName startService(android.content.Intent); */
  { Object, Abstract|Public|Function, "startService", "startService", "(Landroid/content/Intent;)Landroid/content/ComponentName;" },
  /* public abstract boolean stopService(android.content.Intent); */
  { Boolean, Abstract|Public|Function, "stopService", "stopService", "(Landroid/content/Intent;)Z" },
  /* public abstract boolean bindService(android.content.Intent, android.content.ServiceConnection, int); */
  { Boolean, Abstract|Public|Function, "bindService", "bindService", "(Landroid/content/Intent;Landroid/content/ServiceConnection;I)Z" },
  /* public abstract void unbindService(android.content.ServiceConnection); */
  { Void, Abstract|Public|Function, "unbindService", "unbindService", "(Landroid/content/ServiceConnection;)V" },
  /* public abstract boolean startInstrumentation(android.content.ComponentName, java.lang.String, android.os.Bundle); */
  { Boolean, Abstract|Public|Function, "startInstrumentation", "startInstrumentation", "(Landroid/content/ComponentName;Ljava/lang/String;Landroid/os/Bundle;)Z" },
  /* public abstract java.lang.Object getSystemService(java.lang.String); */
  { Object, Abstract|Public|Function, "getSystemService", "getSystemService", "(Ljava/lang/String;)Ljava/lang/Object;" },
  /* public abstract int checkPermission(java.lang.String, int, int); */
  { Int, Abstract|Public|Function, "checkPermission", "checkPermission", "(Ljava/lang/String;II)I" },
  /* public abstract int checkCallingPermission(java.lang.String); */
  { Int, Abstract|Public|Function, "checkCallingPermission", "checkCallingPermission", "(Ljava/lang/String;)I" },
  /* public abstract int checkCallingOrSelfPermission(java.lang.String); */
  { Int, Abstract|Public|Function, "checkCallingOrSelfPermission", "checkCallingOrSelfPermission", "(Ljava/lang/String;)I" },
  /* public abstract void enforcePermission(java.lang.String, int, int, java.lang.String); */
  { Void, Abstract|Public|Function, "enforcePermission", "enforcePermission", "(Ljava/lang/String;IILjava/lang/String;)V" },
  /* public abstract void enforceCallingPermission(java.lang.String, java.lang.String); */
  { Void, Abstract|Public|Function, "enforceCallingPermission", "enforceCallingPermission", "(Ljava/lang/String;Ljava/lang/String;)V" },
  /* public abstract void enforceCallingOrSelfPermission(java.lang.String, java.lang.String); */
  { Void, Abstract|Public|Function, "enforceCallingOrSelfPermission", "enforceCallingOrSelfPermission", "(Ljava/lang/String;Ljava/lang/String;)V" },
  /* public abstract void grantUriPermission(java.lang.String, android.net.Uri, int); */
  { Void, Abstract|Public|Function, "grantUriPermission", "grantUriPermission", "(Ljava/lang/String;Landroid/net/Uri;I)V" },
  /* public abstract void revokeUriPermission(android.net.Uri, int); */
  { Void, Abstract|Public|Function, "revokeUriPermission", "revokeUriPermission", "(Landroid/net/Uri;I)V" },
  /* public abstract int checkUriPermission(android.net.Uri, int, int, int); */
  { Int, Abstract|Public|Function, "checkUriPermission", "checkUriPermission", "(Landroid/net/Uri;III)I" },
  /* public abstract int checkCallingUriPermission(android.net.Uri, int); */
  { Int, Abstract|Public|Function, "checkCallingUriPermission", "checkCallingUriPermission", "(Landroid/net/Uri;I)I" },
  /* public abstract int checkCallingOrSelfUriPermission(android.net.Uri, int); */
  { Int, Abstract|Public|Function, "checkCallingOrSelfUriPermission", "checkCallingOrSelfUriPermission", "(Landroid/net/Uri;I)I" },
  /* public abstract int checkUriPermission(android.net.Uri, java.lang.String, java.lang.String, int, int, int); */
  { Int, Abstract|Public|Function, "checkUriPermission_9", "checkUriPermission", "(Landroid/net/Uri;Ljava/lang/String;Ljava/lang/String;III)I" },
  /* public abstract void enforceUriPermission(android.net.Uri, int, int, int, java.lang.String); */
  { Void, Abstract|Public|Function, "enforceUriPermission", "enforceUriPermission", "(Landroid/net/Uri;IIILjava/lang/String;)V" },
  /* public abstract void enforceCallingUriPermission(android.net.Uri, int, java.lang.String); */
  { Void, Abstract|Public|Function, "enforceCallingUriPermission", "enforceCallingUriPermission", "(Landroid/net/Uri;ILjava/lang/String;)V" },
  /* public abstract void enforceCallingOrSelfUriPermission(android.net.Uri, int, java.lang.String); */
  { Void, Abstract|Public|Function, "enforceCallingOrSelfUriPermission", "enforceCallingOrSelfUriPermission", "(Landroid/net/Uri;ILjava/lang/String;)V" },
  /* public abstract void enforceUriPermission(android.net.Uri, java.lang.String, java.lang.String, int, int, int, java.lang.String); */
  { Void, Abstract|Public|Function, "enforceUriPermission_10", "enforceUriPermission", "(Landroid/net/Uri;Ljava/lang/String;Ljava/lang/String;IIILjava/lang/String;)V" },
  /* public abstract android.content.Context createPackageContext(java.lang.String, int)   throws android.content.pm.PackageManager$NameNotFoundException; */
  { Object, Abstract|Public|Function, "createPackageContext", "createPackageContext", "(Ljava/lang/String;I)Landroid/content/Context;" },
  /* public boolean isRestricted(); */
  { Boolean, Public|Function, "isRestricted", "isRestricted", "()Z" },
};

static JavaObjectDesc Context_Desc = {
  Context,
  sizeof(Context)/sizeof(Context[0])
};

#endif /*_Context_genheader*/

