/*
 * This file is automatically generated at Mon, 12 Aug 2013 14:47:22 +0300
 *
 * Class: android.app.NotificationManager
 * Jar: /home/D.Iakovliev/android/android-sdk-linux/platforms/android-14/android.jar
 *
 * !!!! DO NOT EDIT THIS FILE !!!!
 */
#ifndef _NotificationManager_genheader
#define _NotificationManager_genheader

static JavaMember NotificationManager[] = {
  /* android.app.NotificationManager(); */
  { Void, Private|Constructor, "<init>", "<init>", "()V" },
  /* public void notify(int, android.app.Notification); */
  { Void, Public|Function, "notify", "notify", "(ILandroid/app/Notification;)V" },
  /* public void notify(java.lang.String, int, android.app.Notification); */
  { Void, Public|Function, "notify_0", "notify", "(Ljava/lang/String;ILandroid/app/Notification;)V" },
  /* public void cancel(int); */
  { Void, Public|Function, "cancel", "cancel", "(I)V" },
  /* public void cancel(java.lang.String, int); */
  { Void, Public|Function, "cancel_1", "cancel", "(Ljava/lang/String;I)V" },
  /* public void cancelAll(); */
  { Void, Public|Function, "cancelAll", "cancelAll", "()V" },
};

static JavaObjectDesc NotificationManager_Desc = {
  NotificationManager,
  sizeof(NotificationManager)/sizeof(NotificationManager[0])
};

#endif /*_NotificationManager_genheader*/

